/**
 * List of EMBL-EBI "Data resources" (excludes "Tools").
 * Source: https://www.ebi.ac.uk/services/data-resources-and-tools/
 * (filtered to Type = "Data resources"), captured 2026-07-13.
 * 55 entries total.
 *
 * If EMBL-EBI adds/removes/renames resources, update this list to match
 * the live page's "Data resources" filter.
 */
const EBI_DATA_RESOURCES = [
  { name: "International Genome Sample Resource", url: "http://www.1000genomes.org/" },
  { name: "AlphaFold DB", url: "https://alphafold.ebi.ac.uk/" },
  { name: "AMR portal", url: "https://www.ebi.ac.uk/amr" },
  { name: "BioImage Archive", url: "https://www.ebi.ac.uk/bioimage-archive/" },
  { name: "BioModels", url: "https://www.ebi.ac.uk/biomodels" },
  { name: "BioSamples", url: "https://www.ebi.ac.uk/biosamples/" },
  { name: "BioStudies Database", url: "https://www.ebi.ac.uk/biostudies" },
  { name: "CancerModels.Org", url: "https://www.cancermodels.org/" },
  { name: "ChEBI", url: "https://www.ebi.ac.uk/chebi" },
  { name: "ChEMBL", url: "https://www.ebi.ac.uk/chembl" },
  { name: "Complex Portal", url: "https://www.ebi.ac.uk/complexportal" },
  { name: "DECIPHER", url: "https://www.deciphergenomics.org/" },
  { name: "EFO", url: "https://www.ebi.ac.uk/efo" },
  { name: "EGA", url: "https://ega-archive.org/" },
  { name: "EMDB", url: "https://www.ebi.ac.uk/pdbe/emdb/" },
  { name: "EMPIAR", url: "https://www.ebi.ac.uk/pdbe/emdb/empiar/" },
  { name: "ENA", url: "https://www.ebi.ac.uk/ena/" },
  { name: "Ensembl", url: "https://www.ensembl.org/" },
  { name: "Ensembl Genomes", url: "https://www.ensemblgenomes.org/" },
  { name: "eQTL Catalogue", url: "https://www.ebi.ac.uk/eqtl/" },
  { name: "Europe PMC", url: "https://europepmc.org/" },
  { name: "EVA", url: "https://www.ebi.ac.uk/eva" },
  { name: "Expression Atlas", url: "https://www.ebi.ac.uk/gxa" },
  { name: "Gene2Phenotype", url: "https://www.ebi.ac.uk/gene2phenotype" },
  { name: "Gramene", url: "https://www.gramene.org/" },
  { name: "GWAS Catalog", url: "https://www.ebi.ac.uk/gwas/" },
  { name: "Identifiers.org", url: "https://identifiers.org/" },
  { name: "IMPC Portal", url: "https://www.mousephenotype.org/" },
  { name: "IntAct", url: "https://www.ebi.ac.uk/intact" },
  { name: "InterPro", url: "https://www.ebi.ac.uk/interpro" },
  { name: "IPD", url: "https://www.ebi.ac.uk/ipd/" },
  { name: "JDispatcher", url: "http://www.ebi.ac.uk/jdispatcher" },
  { name: "MetaboLights", url: "https://www.ebi.ac.uk/metabolights" },
  { name: "MGnify", url: "https://www.ebi.ac.uk/metagenomics" },
  { name: "MorPhiC", url: "https://morphic.bio/" },
  { name: "OLS", url: "https://www.ebi.ac.uk/ontology-lookup" },
  { name: "OmicsDI", url: "https://omicsdi.org/" },
  { name: "Open Targets Platform", url: "https://platform.opentargets.org/" },
  { name: "PDBe", url: "https://pdbe.org/" },
  { name: "PDBe-KB", url: "https://www.ebi.ac.uk/pdbe/pdbe-kb" },
  { name: "Perturbation Catalogue", url: "https://www.ebi.ac.uk/perturbation-catalogue/" },
  { name: "Pfam", url: "http://pfam.xfam.org/" },
  { name: "PRIDE", url: "https://www.ebi.ac.uk/pride" },
  { name: "QuickGO", url: "https://www.ebi.ac.uk/QuickGO/" },
  { name: "Reactome", url: "https://www.reactome.org/" },
  { name: "Rfam", url: "http://rfam.xfam.org/" },
  { name: "Rhea", url: "https://www.ebi.ac.uk/rhea" },
  { name: "RNAcentral", url: "https://rnacentral.org/" },
  { name: "SBO", url: "https://www.ebi.ac.uk/sbo" },
  { name: "SIFTS", url: "https://www.ebi.ac.uk/pdbe/docs/sifts/" },
  { name: "SureChEMBL", url: "https://www.surechembl.org/" },
  { name: "TreeFam", url: "https://www.treefam.org/" },
  { name: "UniProt", url: "https://www.uniprot.org/" },
  { name: "UniProt-GOA", url: "https://www.ebi.ac.uk/GOA/" },
  { name: "UniSave", url: "https://www.ebi.ac.uk/uniprot/unisave/" },
];
